// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockFloat64ObservableCounterOption creates a new instance of MockFloat64ObservableCounterOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64ObservableCounterOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64ObservableCounterOption {
	mock := &MockFloat64ObservableCounterOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFloat64ObservableCounterOption is an autogenerated mock type for the Float64ObservableCounterOption type
type MockFloat64ObservableCounterOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockFloat64ObservableCounterOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64ObservableCounterOption) EXPECT() *MockFloat64ObservableCounterOption_Expecter {
	return &MockFloat64ObservableCounterOption_Expecter{mock: &_m.Mock}
}

// applyFloat64ObservableCounter provides a mock function for the type MockFloat64ObservableCounterOption
func (_mock *MockFloat64ObservableCounterOption) applyFloat64ObservableCounter(float64ObservableCounterConfig metric.Float64ObservableCounterConfig) metric.Float64ObservableCounterConfig {
	ret := _mock.Called(float64ObservableCounterConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyFloat64ObservableCounter")
	}

	var r0 metric.Float64ObservableCounterConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Float64ObservableCounterConfig) metric.Float64ObservableCounterConfig); ok {
		r0 = returnFunc(float64ObservableCounterConfig)
	} else {
		r0 = ret.Get(0).(metric.Float64ObservableCounterConfig)
	}
	return r0
}

// MockFloat64ObservableCounterOption_applyFloat64ObservableCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyFloat64ObservableCounter'
type MockFloat64ObservableCounterOption_applyFloat64ObservableCounter_Call struct {
	*mock.Call
}

// applyFloat64ObservableCounter is a helper method to define mock.On call
//   - float64ObservableCounterConfig metric.Float64ObservableCounterConfig
func (_e *MockFloat64ObservableCounterOption_Expecter) applyFloat64ObservableCounter(float64ObservableCounterConfig interface{}) *MockFloat64ObservableCounterOption_applyFloat64ObservableCounter_Call {
	return &MockFloat64ObservableCounterOption_applyFloat64ObservableCounter_Call{Call: _e.mock.On("applyFloat64ObservableCounter", float64ObservableCounterConfig)}
}

func (_c *MockFloat64ObservableCounterOption_applyFloat64ObservableCounter_Call) Run(run func(float64ObservableCounterConfig metric.Float64ObservableCounterConfig)) *MockFloat64ObservableCounterOption_applyFloat64ObservableCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Float64ObservableCounterConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Float64ObservableCounterConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFloat64ObservableCounterOption_applyFloat64ObservableCounter_Call) Return(float64ObservableCounterConfig1 metric.Float64ObservableCounterConfig) *MockFloat64ObservableCounterOption_applyFloat64ObservableCounter_Call {
	_c.Call.Return(float64ObservableCounterConfig1)
	return _c
}

func (_c *MockFloat64ObservableCounterOption_applyFloat64ObservableCounter_Call) RunAndReturn(run func(float64ObservableCounterConfig metric.Float64ObservableCounterConfig) metric.Float64ObservableCounterConfig) *MockFloat64ObservableCounterOption_applyFloat64ObservableCounter_Call {
	_c.Call.Return(run)
	return _c
}
