// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockInt64ObservableCounterOption creates a new instance of MockInt64ObservableCounterOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64ObservableCounterOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64ObservableCounterOption {
	mock := &MockInt64ObservableCounterOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInt64ObservableCounterOption is an autogenerated mock type for the Int64ObservableCounterOption type
type MockInt64ObservableCounterOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockInt64ObservableCounterOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64ObservableCounterOption) EXPECT() *MockInt64ObservableCounterOption_Expecter {
	return &MockInt64ObservableCounterOption_Expecter{mock: &_m.Mock}
}

// applyInt64ObservableCounter provides a mock function for the type MockInt64ObservableCounterOption
func (_mock *MockInt64ObservableCounterOption) applyInt64ObservableCounter(int64ObservableCounterConfig metric.Int64ObservableCounterConfig) metric.Int64ObservableCounterConfig {
	ret := _mock.Called(int64ObservableCounterConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyInt64ObservableCounter")
	}

	var r0 metric.Int64ObservableCounterConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Int64ObservableCounterConfig) metric.Int64ObservableCounterConfig); ok {
		r0 = returnFunc(int64ObservableCounterConfig)
	} else {
		r0 = ret.Get(0).(metric.Int64ObservableCounterConfig)
	}
	return r0
}

// MockInt64ObservableCounterOption_applyInt64ObservableCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyInt64ObservableCounter'
type MockInt64ObservableCounterOption_applyInt64ObservableCounter_Call struct {
	*mock.Call
}

// applyInt64ObservableCounter is a helper method to define mock.On call
//   - int64ObservableCounterConfig metric.Int64ObservableCounterConfig
func (_e *MockInt64ObservableCounterOption_Expecter) applyInt64ObservableCounter(int64ObservableCounterConfig interface{}) *MockInt64ObservableCounterOption_applyInt64ObservableCounter_Call {
	return &MockInt64ObservableCounterOption_applyInt64ObservableCounter_Call{Call: _e.mock.On("applyInt64ObservableCounter", int64ObservableCounterConfig)}
}

func (_c *MockInt64ObservableCounterOption_applyInt64ObservableCounter_Call) Run(run func(int64ObservableCounterConfig metric.Int64ObservableCounterConfig)) *MockInt64ObservableCounterOption_applyInt64ObservableCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Int64ObservableCounterConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Int64ObservableCounterConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInt64ObservableCounterOption_applyInt64ObservableCounter_Call) Return(int64ObservableCounterConfig1 metric.Int64ObservableCounterConfig) *MockInt64ObservableCounterOption_applyInt64ObservableCounter_Call {
	_c.Call.Return(int64ObservableCounterConfig1)
	return _c
}

func (_c *MockInt64ObservableCounterOption_applyInt64ObservableCounter_Call) RunAndReturn(run func(int64ObservableCounterConfig metric.Int64ObservableCounterConfig) metric.Int64ObservableCounterConfig) *MockInt64ObservableCounterOption_applyInt64ObservableCounter_Call {
	_c.Call.Return(run)
	return _c
}
