// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockFloat64ObservableUpDownCounter creates a new instance of MockFloat64ObservableUpDownCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64ObservableUpDownCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64ObservableUpDownCounter {
	mock := &MockFloat64ObservableUpDownCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFloat64ObservableUpDownCounter is an autogenerated mock type for the Float64ObservableUpDownCounter type
type MockFloat64ObservableUpDownCounter struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockFloat64ObservableUpDownCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64ObservableUpDownCounter) EXPECT() *MockFloat64ObservableUpDownCounter_Expecter {
	return &MockFloat64ObservableUpDownCounter_Expecter{mock: &_m.Mock}
}

// float64Observable provides a mock function for the type MockFloat64ObservableUpDownCounter
func (_mock *MockFloat64ObservableUpDownCounter) float64Observable() {
	_mock.Called()
	return
}

// MockFloat64ObservableUpDownCounter_float64Observable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'float64Observable'
type MockFloat64ObservableUpDownCounter_float64Observable_Call struct {
	*mock.Call
}

// float64Observable is a helper method to define mock.On call
func (_e *MockFloat64ObservableUpDownCounter_Expecter) float64Observable() *MockFloat64ObservableUpDownCounter_float64Observable_Call {
	return &MockFloat64ObservableUpDownCounter_float64Observable_Call{Call: _e.mock.On("float64Observable")}
}

func (_c *MockFloat64ObservableUpDownCounter_float64Observable_Call) Run(run func()) *MockFloat64ObservableUpDownCounter_float64Observable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFloat64ObservableUpDownCounter_float64Observable_Call) Return() *MockFloat64ObservableUpDownCounter_float64Observable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64ObservableUpDownCounter_float64Observable_Call) RunAndReturn(run func()) *MockFloat64ObservableUpDownCounter_float64Observable_Call {
	_c.Run(run)
	return _c
}

// float64ObservableUpDownCounter provides a mock function for the type MockFloat64ObservableUpDownCounter
func (_mock *MockFloat64ObservableUpDownCounter) float64ObservableUpDownCounter() {
	_mock.Called()
	return
}

// MockFloat64ObservableUpDownCounter_float64ObservableUpDownCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'float64ObservableUpDownCounter'
type MockFloat64ObservableUpDownCounter_float64ObservableUpDownCounter_Call struct {
	*mock.Call
}

// float64ObservableUpDownCounter is a helper method to define mock.On call
func (_e *MockFloat64ObservableUpDownCounter_Expecter) float64ObservableUpDownCounter() *MockFloat64ObservableUpDownCounter_float64ObservableUpDownCounter_Call {
	return &MockFloat64ObservableUpDownCounter_float64ObservableUpDownCounter_Call{Call: _e.mock.On("float64ObservableUpDownCounter")}
}

func (_c *MockFloat64ObservableUpDownCounter_float64ObservableUpDownCounter_Call) Run(run func()) *MockFloat64ObservableUpDownCounter_float64ObservableUpDownCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFloat64ObservableUpDownCounter_float64ObservableUpDownCounter_Call) Return() *MockFloat64ObservableUpDownCounter_float64ObservableUpDownCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64ObservableUpDownCounter_float64ObservableUpDownCounter_Call) RunAndReturn(run func()) *MockFloat64ObservableUpDownCounter_float64ObservableUpDownCounter_Call {
	_c.Run(run)
	return _c
}

// observable provides a mock function for the type MockFloat64ObservableUpDownCounter
func (_mock *MockFloat64ObservableUpDownCounter) observable() {
	_mock.Called()
	return
}

// MockFloat64ObservableUpDownCounter_observable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'observable'
type MockFloat64ObservableUpDownCounter_observable_Call struct {
	*mock.Call
}

// observable is a helper method to define mock.On call
func (_e *MockFloat64ObservableUpDownCounter_Expecter) observable() *MockFloat64ObservableUpDownCounter_observable_Call {
	return &MockFloat64ObservableUpDownCounter_observable_Call{Call: _e.mock.On("observable")}
}

func (_c *MockFloat64ObservableUpDownCounter_observable_Call) Run(run func()) *MockFloat64ObservableUpDownCounter_observable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFloat64ObservableUpDownCounter_observable_Call) Return() *MockFloat64ObservableUpDownCounter_observable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64ObservableUpDownCounter_observable_Call) RunAndReturn(run func()) *MockFloat64ObservableUpDownCounter_observable_Call {
	_c.Run(run)
	return _c
}
