// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockInt64GaugeOption creates a new instance of MockInt64GaugeOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64GaugeOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64GaugeOption {
	mock := &MockInt64GaugeOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInt64GaugeOption is an autogenerated mock type for the Int64GaugeOption type
type MockInt64GaugeOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockInt64GaugeOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64GaugeOption) EXPECT() *MockInt64GaugeOption_Expecter {
	return &MockInt64GaugeOption_Expecter{mock: &_m.Mock}
}

// applyInt64Gauge provides a mock function for the type MockInt64GaugeOption
func (_mock *MockInt64GaugeOption) applyInt64Gauge(int64GaugeConfig metric.Int64GaugeConfig) metric.Int64GaugeConfig {
	ret := _mock.Called(int64GaugeConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyInt64Gauge")
	}

	var r0 metric.Int64GaugeConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Int64GaugeConfig) metric.Int64GaugeConfig); ok {
		r0 = returnFunc(int64GaugeConfig)
	} else {
		r0 = ret.Get(0).(metric.Int64GaugeConfig)
	}
	return r0
}

// MockInt64GaugeOption_applyInt64Gauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyInt64Gauge'
type MockInt64GaugeOption_applyInt64Gauge_Call struct {
	*mock.Call
}

// applyInt64Gauge is a helper method to define mock.On call
//   - int64GaugeConfig metric.Int64GaugeConfig
func (_e *MockInt64GaugeOption_Expecter) applyInt64Gauge(int64GaugeConfig interface{}) *MockInt64GaugeOption_applyInt64Gauge_Call {
	return &MockInt64GaugeOption_applyInt64Gauge_Call{Call: _e.mock.On("applyInt64Gauge", int64GaugeConfig)}
}

func (_c *MockInt64GaugeOption_applyInt64Gauge_Call) Run(run func(int64GaugeConfig metric.Int64GaugeConfig)) *MockInt64GaugeOption_applyInt64Gauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Int64GaugeConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Int64GaugeConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInt64GaugeOption_applyInt64Gauge_Call) Return(int64GaugeConfig1 metric.Int64GaugeConfig) *MockInt64GaugeOption_applyInt64Gauge_Call {
	_c.Call.Return(int64GaugeConfig1)
	return _c
}

func (_c *MockInt64GaugeOption_applyInt64Gauge_Call) RunAndReturn(run func(int64GaugeConfig metric.Int64GaugeConfig) metric.Int64GaugeConfig) *MockInt64GaugeOption_applyInt64Gauge_Call {
	_c.Call.Return(run)
	return _c
}
