// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockInt64ObservableOption creates a new instance of MockInt64ObservableOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64ObservableOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64ObservableOption {
	mock := &MockInt64ObservableOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInt64ObservableOption is an autogenerated mock type for the Int64ObservableOption type
type MockInt64ObservableOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockInt64ObservableOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64ObservableOption) EXPECT() *MockInt64ObservableOption_Expecter {
	return &MockInt64ObservableOption_Expecter{mock: &_m.Mock}
}

// applyInt64ObservableCounter provides a mock function for the type MockInt64ObservableOption
func (_mock *MockInt64ObservableOption) applyInt64ObservableCounter(int64ObservableCounterConfig metric.Int64ObservableCounterConfig) metric.Int64ObservableCounterConfig {
	ret := _mock.Called(int64ObservableCounterConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyInt64ObservableCounter")
	}

	var r0 metric.Int64ObservableCounterConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Int64ObservableCounterConfig) metric.Int64ObservableCounterConfig); ok {
		r0 = returnFunc(int64ObservableCounterConfig)
	} else {
		r0 = ret.Get(0).(metric.Int64ObservableCounterConfig)
	}
	return r0
}

// MockInt64ObservableOption_applyInt64ObservableCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyInt64ObservableCounter'
type MockInt64ObservableOption_applyInt64ObservableCounter_Call struct {
	*mock.Call
}

// applyInt64ObservableCounter is a helper method to define mock.On call
//   - int64ObservableCounterConfig metric.Int64ObservableCounterConfig
func (_e *MockInt64ObservableOption_Expecter) applyInt64ObservableCounter(int64ObservableCounterConfig interface{}) *MockInt64ObservableOption_applyInt64ObservableCounter_Call {
	return &MockInt64ObservableOption_applyInt64ObservableCounter_Call{Call: _e.mock.On("applyInt64ObservableCounter", int64ObservableCounterConfig)}
}

func (_c *MockInt64ObservableOption_applyInt64ObservableCounter_Call) Run(run func(int64ObservableCounterConfig metric.Int64ObservableCounterConfig)) *MockInt64ObservableOption_applyInt64ObservableCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Int64ObservableCounterConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Int64ObservableCounterConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInt64ObservableOption_applyInt64ObservableCounter_Call) Return(int64ObservableCounterConfig1 metric.Int64ObservableCounterConfig) *MockInt64ObservableOption_applyInt64ObservableCounter_Call {
	_c.Call.Return(int64ObservableCounterConfig1)
	return _c
}

func (_c *MockInt64ObservableOption_applyInt64ObservableCounter_Call) RunAndReturn(run func(int64ObservableCounterConfig metric.Int64ObservableCounterConfig) metric.Int64ObservableCounterConfig) *MockInt64ObservableOption_applyInt64ObservableCounter_Call {
	_c.Call.Return(run)
	return _c
}

// applyInt64ObservableGauge provides a mock function for the type MockInt64ObservableOption
func (_mock *MockInt64ObservableOption) applyInt64ObservableGauge(int64ObservableGaugeConfig metric.Int64ObservableGaugeConfig) metric.Int64ObservableGaugeConfig {
	ret := _mock.Called(int64ObservableGaugeConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyInt64ObservableGauge")
	}

	var r0 metric.Int64ObservableGaugeConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Int64ObservableGaugeConfig) metric.Int64ObservableGaugeConfig); ok {
		r0 = returnFunc(int64ObservableGaugeConfig)
	} else {
		r0 = ret.Get(0).(metric.Int64ObservableGaugeConfig)
	}
	return r0
}

// MockInt64ObservableOption_applyInt64ObservableGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyInt64ObservableGauge'
type MockInt64ObservableOption_applyInt64ObservableGauge_Call struct {
	*mock.Call
}

// applyInt64ObservableGauge is a helper method to define mock.On call
//   - int64ObservableGaugeConfig metric.Int64ObservableGaugeConfig
func (_e *MockInt64ObservableOption_Expecter) applyInt64ObservableGauge(int64ObservableGaugeConfig interface{}) *MockInt64ObservableOption_applyInt64ObservableGauge_Call {
	return &MockInt64ObservableOption_applyInt64ObservableGauge_Call{Call: _e.mock.On("applyInt64ObservableGauge", int64ObservableGaugeConfig)}
}

func (_c *MockInt64ObservableOption_applyInt64ObservableGauge_Call) Run(run func(int64ObservableGaugeConfig metric.Int64ObservableGaugeConfig)) *MockInt64ObservableOption_applyInt64ObservableGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Int64ObservableGaugeConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Int64ObservableGaugeConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInt64ObservableOption_applyInt64ObservableGauge_Call) Return(int64ObservableGaugeConfig1 metric.Int64ObservableGaugeConfig) *MockInt64ObservableOption_applyInt64ObservableGauge_Call {
	_c.Call.Return(int64ObservableGaugeConfig1)
	return _c
}

func (_c *MockInt64ObservableOption_applyInt64ObservableGauge_Call) RunAndReturn(run func(int64ObservableGaugeConfig metric.Int64ObservableGaugeConfig) metric.Int64ObservableGaugeConfig) *MockInt64ObservableOption_applyInt64ObservableGauge_Call {
	_c.Call.Return(run)
	return _c
}

// applyInt64ObservableUpDownCounter provides a mock function for the type MockInt64ObservableOption
func (_mock *MockInt64ObservableOption) applyInt64ObservableUpDownCounter(int64ObservableUpDownCounterConfig metric.Int64ObservableUpDownCounterConfig) metric.Int64ObservableUpDownCounterConfig {
	ret := _mock.Called(int64ObservableUpDownCounterConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyInt64ObservableUpDownCounter")
	}

	var r0 metric.Int64ObservableUpDownCounterConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Int64ObservableUpDownCounterConfig) metric.Int64ObservableUpDownCounterConfig); ok {
		r0 = returnFunc(int64ObservableUpDownCounterConfig)
	} else {
		r0 = ret.Get(0).(metric.Int64ObservableUpDownCounterConfig)
	}
	return r0
}

// MockInt64ObservableOption_applyInt64ObservableUpDownCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyInt64ObservableUpDownCounter'
type MockInt64ObservableOption_applyInt64ObservableUpDownCounter_Call struct {
	*mock.Call
}

// applyInt64ObservableUpDownCounter is a helper method to define mock.On call
//   - int64ObservableUpDownCounterConfig metric.Int64ObservableUpDownCounterConfig
func (_e *MockInt64ObservableOption_Expecter) applyInt64ObservableUpDownCounter(int64ObservableUpDownCounterConfig interface{}) *MockInt64ObservableOption_applyInt64ObservableUpDownCounter_Call {
	return &MockInt64ObservableOption_applyInt64ObservableUpDownCounter_Call{Call: _e.mock.On("applyInt64ObservableUpDownCounter", int64ObservableUpDownCounterConfig)}
}

func (_c *MockInt64ObservableOption_applyInt64ObservableUpDownCounter_Call) Run(run func(int64ObservableUpDownCounterConfig metric.Int64ObservableUpDownCounterConfig)) *MockInt64ObservableOption_applyInt64ObservableUpDownCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Int64ObservableUpDownCounterConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Int64ObservableUpDownCounterConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInt64ObservableOption_applyInt64ObservableUpDownCounter_Call) Return(int64ObservableUpDownCounterConfig1 metric.Int64ObservableUpDownCounterConfig) *MockInt64ObservableOption_applyInt64ObservableUpDownCounter_Call {
	_c.Call.Return(int64ObservableUpDownCounterConfig1)
	return _c
}

func (_c *MockInt64ObservableOption_applyInt64ObservableUpDownCounter_Call) RunAndReturn(run func(int64ObservableUpDownCounterConfig metric.Int64ObservableUpDownCounterConfig) metric.Int64ObservableUpDownCounterConfig) *MockInt64ObservableOption_applyInt64ObservableUpDownCounter_Call {
	_c.Call.Return(run)
	return _c
}
