// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockInt64HistogramOption creates a new instance of MockInt64HistogramOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64HistogramOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64HistogramOption {
	mock := &MockInt64HistogramOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInt64HistogramOption is an autogenerated mock type for the Int64HistogramOption type
type MockInt64HistogramOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockInt64HistogramOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64HistogramOption) EXPECT() *MockInt64HistogramOption_Expecter {
	return &MockInt64HistogramOption_Expecter{mock: &_m.Mock}
}

// applyInt64Histogram provides a mock function for the type MockInt64HistogramOption
func (_mock *MockInt64HistogramOption) applyInt64Histogram(int64HistogramConfig metric.Int64HistogramConfig) metric.Int64HistogramConfig {
	ret := _mock.Called(int64HistogramConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyInt64Histogram")
	}

	var r0 metric.Int64HistogramConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Int64HistogramConfig) metric.Int64HistogramConfig); ok {
		r0 = returnFunc(int64HistogramConfig)
	} else {
		r0 = ret.Get(0).(metric.Int64HistogramConfig)
	}
	return r0
}

// MockInt64HistogramOption_applyInt64Histogram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyInt64Histogram'
type MockInt64HistogramOption_applyInt64Histogram_Call struct {
	*mock.Call
}

// applyInt64Histogram is a helper method to define mock.On call
//   - int64HistogramConfig metric.Int64HistogramConfig
func (_e *MockInt64HistogramOption_Expecter) applyInt64Histogram(int64HistogramConfig interface{}) *MockInt64HistogramOption_applyInt64Histogram_Call {
	return &MockInt64HistogramOption_applyInt64Histogram_Call{Call: _e.mock.On("applyInt64Histogram", int64HistogramConfig)}
}

func (_c *MockInt64HistogramOption_applyInt64Histogram_Call) Run(run func(int64HistogramConfig metric.Int64HistogramConfig)) *MockInt64HistogramOption_applyInt64Histogram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Int64HistogramConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Int64HistogramConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInt64HistogramOption_applyInt64Histogram_Call) Return(int64HistogramConfig1 metric.Int64HistogramConfig) *MockInt64HistogramOption_applyInt64Histogram_Call {
	_c.Call.Return(int64HistogramConfig1)
	return _c
}

func (_c *MockInt64HistogramOption_applyInt64Histogram_Call) RunAndReturn(run func(int64HistogramConfig metric.Int64HistogramConfig) metric.Int64HistogramConfig) *MockInt64HistogramOption_applyInt64Histogram_Call {
	_c.Call.Return(run)
	return _c
}
