// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockFloat64ObservableOption creates a new instance of MockFloat64ObservableOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64ObservableOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64ObservableOption {
	mock := &MockFloat64ObservableOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFloat64ObservableOption is an autogenerated mock type for the Float64ObservableOption type
type MockFloat64ObservableOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockFloat64ObservableOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64ObservableOption) EXPECT() *MockFloat64ObservableOption_Expecter {
	return &MockFloat64ObservableOption_Expecter{mock: &_m.Mock}
}

// applyFloat64ObservableCounter provides a mock function for the type MockFloat64ObservableOption
func (_mock *MockFloat64ObservableOption) applyFloat64ObservableCounter(float64ObservableCounterConfig metric.Float64ObservableCounterConfig) metric.Float64ObservableCounterConfig {
	ret := _mock.Called(float64ObservableCounterConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyFloat64ObservableCounter")
	}

	var r0 metric.Float64ObservableCounterConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Float64ObservableCounterConfig) metric.Float64ObservableCounterConfig); ok {
		r0 = returnFunc(float64ObservableCounterConfig)
	} else {
		r0 = ret.Get(0).(metric.Float64ObservableCounterConfig)
	}
	return r0
}

// MockFloat64ObservableOption_applyFloat64ObservableCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyFloat64ObservableCounter'
type MockFloat64ObservableOption_applyFloat64ObservableCounter_Call struct {
	*mock.Call
}

// applyFloat64ObservableCounter is a helper method to define mock.On call
//   - float64ObservableCounterConfig metric.Float64ObservableCounterConfig
func (_e *MockFloat64ObservableOption_Expecter) applyFloat64ObservableCounter(float64ObservableCounterConfig interface{}) *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call {
	return &MockFloat64ObservableOption_applyFloat64ObservableCounter_Call{Call: _e.mock.On("applyFloat64ObservableCounter", float64ObservableCounterConfig)}
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call) Run(run func(float64ObservableCounterConfig metric.Float64ObservableCounterConfig)) *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Float64ObservableCounterConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Float64ObservableCounterConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call) Return(float64ObservableCounterConfig1 metric.Float64ObservableCounterConfig) *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call {
	_c.Call.Return(float64ObservableCounterConfig1)
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call) RunAndReturn(run func(float64ObservableCounterConfig metric.Float64ObservableCounterConfig) metric.Float64ObservableCounterConfig) *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call {
	_c.Call.Return(run)
	return _c
}

// applyFloat64ObservableGauge provides a mock function for the type MockFloat64ObservableOption
func (_mock *MockFloat64ObservableOption) applyFloat64ObservableGauge(float64ObservableGaugeConfig metric.Float64ObservableGaugeConfig) metric.Float64ObservableGaugeConfig {
	ret := _mock.Called(float64ObservableGaugeConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyFloat64ObservableGauge")
	}

	var r0 metric.Float64ObservableGaugeConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Float64ObservableGaugeConfig) metric.Float64ObservableGaugeConfig); ok {
		r0 = returnFunc(float64ObservableGaugeConfig)
	} else {
		r0 = ret.Get(0).(metric.Float64ObservableGaugeConfig)
	}
	return r0
}

// MockFloat64ObservableOption_applyFloat64ObservableGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyFloat64ObservableGauge'
type MockFloat64ObservableOption_applyFloat64ObservableGauge_Call struct {
	*mock.Call
}

// applyFloat64ObservableGauge is a helper method to define mock.On call
//   - float64ObservableGaugeConfig metric.Float64ObservableGaugeConfig
func (_e *MockFloat64ObservableOption_Expecter) applyFloat64ObservableGauge(float64ObservableGaugeConfig interface{}) *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call {
	return &MockFloat64ObservableOption_applyFloat64ObservableGauge_Call{Call: _e.mock.On("applyFloat64ObservableGauge", float64ObservableGaugeConfig)}
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call) Run(run func(float64ObservableGaugeConfig metric.Float64ObservableGaugeConfig)) *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Float64ObservableGaugeConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Float64ObservableGaugeConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call) Return(float64ObservableGaugeConfig1 metric.Float64ObservableGaugeConfig) *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call {
	_c.Call.Return(float64ObservableGaugeConfig1)
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call) RunAndReturn(run func(float64ObservableGaugeConfig metric.Float64ObservableGaugeConfig) metric.Float64ObservableGaugeConfig) *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call {
	_c.Call.Return(run)
	return _c
}

// applyFloat64ObservableUpDownCounter provides a mock function for the type MockFloat64ObservableOption
func (_mock *MockFloat64ObservableOption) applyFloat64ObservableUpDownCounter(float64ObservableUpDownCounterConfig metric.Float64ObservableUpDownCounterConfig) metric.Float64ObservableUpDownCounterConfig {
	ret := _mock.Called(float64ObservableUpDownCounterConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyFloat64ObservableUpDownCounter")
	}

	var r0 metric.Float64ObservableUpDownCounterConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Float64ObservableUpDownCounterConfig) metric.Float64ObservableUpDownCounterConfig); ok {
		r0 = returnFunc(float64ObservableUpDownCounterConfig)
	} else {
		r0 = ret.Get(0).(metric.Float64ObservableUpDownCounterConfig)
	}
	return r0
}

// MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyFloat64ObservableUpDownCounter'
type MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call struct {
	*mock.Call
}

// applyFloat64ObservableUpDownCounter is a helper method to define mock.On call
//   - float64ObservableUpDownCounterConfig metric.Float64ObservableUpDownCounterConfig
func (_e *MockFloat64ObservableOption_Expecter) applyFloat64ObservableUpDownCounter(float64ObservableUpDownCounterConfig interface{}) *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call {
	return &MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call{Call: _e.mock.On("applyFloat64ObservableUpDownCounter", float64ObservableUpDownCounterConfig)}
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call) Run(run func(float64ObservableUpDownCounterConfig metric.Float64ObservableUpDownCounterConfig)) *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Float64ObservableUpDownCounterConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Float64ObservableUpDownCounterConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call) Return(float64ObservableUpDownCounterConfig1 metric.Float64ObservableUpDownCounterConfig) *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call {
	_c.Call.Return(float64ObservableUpDownCounterConfig1)
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call) RunAndReturn(run func(float64ObservableUpDownCounterConfig metric.Float64ObservableUpDownCounterConfig) metric.Float64ObservableUpDownCounterConfig) *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call {
	_c.Call.Return(run)
	return _c
}
