// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockFloat64ObservableGaugeOption creates a new instance of MockFloat64ObservableGaugeOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64ObservableGaugeOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64ObservableGaugeOption {
	mock := &MockFloat64ObservableGaugeOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFloat64ObservableGaugeOption is an autogenerated mock type for the Float64ObservableGaugeOption type
type MockFloat64ObservableGaugeOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockFloat64ObservableGaugeOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64ObservableGaugeOption) EXPECT() *MockFloat64ObservableGaugeOption_Expecter {
	return &MockFloat64ObservableGaugeOption_Expecter{mock: &_m.Mock}
}

// applyFloat64ObservableGauge provides a mock function for the type MockFloat64ObservableGaugeOption
func (_mock *MockFloat64ObservableGaugeOption) applyFloat64ObservableGauge(float64ObservableGaugeConfig metric.Float64ObservableGaugeConfig) metric.Float64ObservableGaugeConfig {
	ret := _mock.Called(float64ObservableGaugeConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyFloat64ObservableGauge")
	}

	var r0 metric.Float64ObservableGaugeConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Float64ObservableGaugeConfig) metric.Float64ObservableGaugeConfig); ok {
		r0 = returnFunc(float64ObservableGaugeConfig)
	} else {
		r0 = ret.Get(0).(metric.Float64ObservableGaugeConfig)
	}
	return r0
}

// MockFloat64ObservableGaugeOption_applyFloat64ObservableGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyFloat64ObservableGauge'
type MockFloat64ObservableGaugeOption_applyFloat64ObservableGauge_Call struct {
	*mock.Call
}

// applyFloat64ObservableGauge is a helper method to define mock.On call
//   - float64ObservableGaugeConfig metric.Float64ObservableGaugeConfig
func (_e *MockFloat64ObservableGaugeOption_Expecter) applyFloat64ObservableGauge(float64ObservableGaugeConfig interface{}) *MockFloat64ObservableGaugeOption_applyFloat64ObservableGauge_Call {
	return &MockFloat64ObservableGaugeOption_applyFloat64ObservableGauge_Call{Call: _e.mock.On("applyFloat64ObservableGauge", float64ObservableGaugeConfig)}
}

func (_c *MockFloat64ObservableGaugeOption_applyFloat64ObservableGauge_Call) Run(run func(float64ObservableGaugeConfig metric.Float64ObservableGaugeConfig)) *MockFloat64ObservableGaugeOption_applyFloat64ObservableGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Float64ObservableGaugeConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Float64ObservableGaugeConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFloat64ObservableGaugeOption_applyFloat64ObservableGauge_Call) Return(float64ObservableGaugeConfig1 metric.Float64ObservableGaugeConfig) *MockFloat64ObservableGaugeOption_applyFloat64ObservableGauge_Call {
	_c.Call.Return(float64ObservableGaugeConfig1)
	return _c
}

func (_c *MockFloat64ObservableGaugeOption_applyFloat64ObservableGauge_Call) RunAndReturn(run func(float64ObservableGaugeConfig metric.Float64ObservableGaugeConfig) metric.Float64ObservableGaugeConfig) *MockFloat64ObservableGaugeOption_applyFloat64ObservableGauge_Call {
	_c.Call.Return(run)
	return _c
}
