// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockInt64CounterOption creates a new instance of MockInt64CounterOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64CounterOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64CounterOption {
	mock := &MockInt64CounterOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInt64CounterOption is an autogenerated mock type for the Int64CounterOption type
type MockInt64CounterOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockInt64CounterOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64CounterOption) EXPECT() *MockInt64CounterOption_Expecter {
	return &MockInt64CounterOption_Expecter{mock: &_m.Mock}
}

// applyInt64Counter provides a mock function for the type MockInt64CounterOption
func (_mock *MockInt64CounterOption) applyInt64Counter(int64CounterConfig metric.Int64CounterConfig) metric.Int64CounterConfig {
	ret := _mock.Called(int64CounterConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyInt64Counter")
	}

	var r0 metric.Int64CounterConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Int64CounterConfig) metric.Int64CounterConfig); ok {
		r0 = returnFunc(int64CounterConfig)
	} else {
		r0 = ret.Get(0).(metric.Int64CounterConfig)
	}
	return r0
}

// MockInt64CounterOption_applyInt64Counter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyInt64Counter'
type MockInt64CounterOption_applyInt64Counter_Call struct {
	*mock.Call
}

// applyInt64Counter is a helper method to define mock.On call
//   - int64CounterConfig metric.Int64CounterConfig
func (_e *MockInt64CounterOption_Expecter) applyInt64Counter(int64CounterConfig interface{}) *MockInt64CounterOption_applyInt64Counter_Call {
	return &MockInt64CounterOption_applyInt64Counter_Call{Call: _e.mock.On("applyInt64Counter", int64CounterConfig)}
}

func (_c *MockInt64CounterOption_applyInt64Counter_Call) Run(run func(int64CounterConfig metric.Int64CounterConfig)) *MockInt64CounterOption_applyInt64Counter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Int64CounterConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Int64CounterConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInt64CounterOption_applyInt64Counter_Call) Return(int64CounterConfig1 metric.Int64CounterConfig) *MockInt64CounterOption_applyInt64Counter_Call {
	_c.Call.Return(int64CounterConfig1)
	return _c
}

func (_c *MockInt64CounterOption_applyInt64Counter_Call) RunAndReturn(run func(int64CounterConfig metric.Int64CounterConfig) metric.Int64CounterConfig) *MockInt64CounterOption_applyInt64Counter_Call {
	_c.Call.Return(run)
	return _c
}
