// Code generated by mockery v2.50.1. DO NOT EDIT.

package metric

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metric "go.opentelemetry.io/otel/metric"
)

// MockCallback is an autogenerated mock type for the Callback type
type MockCallback struct {
	mock.Mock
}

type MockCallback_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCallback) EXPECT() *MockCallback_Expecter {
	return &MockCallback_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MockCallback) Execute(_a0 context.Context, _a1 metric.Observer) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metric.Observer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCallback_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCallback_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 metric.Observer
func (_e *MockCallback_Expecter) Execute(_a0 interface{}, _a1 interface{}) *MockCallback_Execute_Call {
	return &MockCallback_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *MockCallback_Execute_Call) Run(run func(_a0 context.Context, _a1 metric.Observer)) *MockCallback_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metric.Observer))
	})
	return _c
}

func (_c *MockCallback_Execute_Call) Return(_a0 error) *MockCallback_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCallback_Execute_Call) RunAndReturn(run func(context.Context, metric.Observer) error) *MockCallback_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCallback creates a new instance of MockCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCallback(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCallback {
	mock := &MockCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
