// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockRegistration creates a new instance of MockRegistration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistration(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistration {
	mock := &MockRegistration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistration is an autogenerated mock type for the Registration type
type MockRegistration struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockRegistration_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistration) EXPECT() *MockRegistration_Expecter {
	return &MockRegistration_Expecter{mock: &_m.Mock}
}

// Unregister provides a mock function for the type MockRegistration
func (_mock *MockRegistration) Unregister() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unregister")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistration_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockRegistration_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
func (_e *MockRegistration_Expecter) Unregister() *MockRegistration_Unregister_Call {
	return &MockRegistration_Unregister_Call{Call: _e.mock.On("Unregister")}
}

func (_c *MockRegistration_Unregister_Call) Run(run func()) *MockRegistration_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistration_Unregister_Call) Return(err error) *MockRegistration_Unregister_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistration_Unregister_Call) RunAndReturn(run func() error) *MockRegistration_Unregister_Call {
	_c.Call.Return(run)
	return _c
}

// registration provides a mock function for the type MockRegistration
func (_mock *MockRegistration) registration() {
	_mock.Called()
	return
}

// MockRegistration_registration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'registration'
type MockRegistration_registration_Call struct {
	*mock.Call
}

// registration is a helper method to define mock.On call
func (_e *MockRegistration_Expecter) registration() *MockRegistration_registration_Call {
	return &MockRegistration_registration_Call{Call: _e.mock.On("registration")}
}

func (_c *MockRegistration_registration_Call) Run(run func()) *MockRegistration_registration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistration_registration_Call) Return() *MockRegistration_registration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistration_registration_Call) RunAndReturn(run func()) *MockRegistration_registration_Call {
	_c.Run(run)
	return _c
}
