// Code generated by mockery v2.50.1. DO NOT EDIT.

package metric

import (
	mock "github.com/stretchr/testify/mock"
	metric "go.opentelemetry.io/otel/metric"
)

// MockMeasurementOption is an autogenerated mock type for the MeasurementOption type
type MockMeasurementOption struct {
	mock.Mock
}

type MockMeasurementOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMeasurementOption) EXPECT() *MockMeasurementOption_Expecter {
	return &MockMeasurementOption_Expecter{mock: &_m.Mock}
}

// applyAdd provides a mock function with given fields: _a0
func (_m *MockMeasurementOption) applyAdd(_a0 metric.AddConfig) metric.AddConfig {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for applyAdd")
	}

	var r0 metric.AddConfig
	if rf, ok := ret.Get(0).(func(metric.AddConfig) metric.AddConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(metric.AddConfig)
	}

	return r0
}

// MockMeasurementOption_applyAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyAdd'
type MockMeasurementOption_applyAdd_Call struct {
	*mock.Call
}

// applyAdd is a helper method to define mock.On call
//   - _a0 metric.AddConfig
func (_e *MockMeasurementOption_Expecter) applyAdd(_a0 interface{}) *MockMeasurementOption_applyAdd_Call {
	return &MockMeasurementOption_applyAdd_Call{Call: _e.mock.On("applyAdd", _a0)}
}

func (_c *MockMeasurementOption_applyAdd_Call) Run(run func(_a0 metric.AddConfig)) *MockMeasurementOption_applyAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metric.AddConfig))
	})
	return _c
}

func (_c *MockMeasurementOption_applyAdd_Call) Return(_a0 metric.AddConfig) *MockMeasurementOption_applyAdd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMeasurementOption_applyAdd_Call) RunAndReturn(run func(metric.AddConfig) metric.AddConfig) *MockMeasurementOption_applyAdd_Call {
	_c.Call.Return(run)
	return _c
}

// applyObserve provides a mock function with given fields: _a0
func (_m *MockMeasurementOption) applyObserve(_a0 metric.ObserveConfig) metric.ObserveConfig {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for applyObserve")
	}

	var r0 metric.ObserveConfig
	if rf, ok := ret.Get(0).(func(metric.ObserveConfig) metric.ObserveConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(metric.ObserveConfig)
	}

	return r0
}

// MockMeasurementOption_applyObserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyObserve'
type MockMeasurementOption_applyObserve_Call struct {
	*mock.Call
}

// applyObserve is a helper method to define mock.On call
//   - _a0 metric.ObserveConfig
func (_e *MockMeasurementOption_Expecter) applyObserve(_a0 interface{}) *MockMeasurementOption_applyObserve_Call {
	return &MockMeasurementOption_applyObserve_Call{Call: _e.mock.On("applyObserve", _a0)}
}

func (_c *MockMeasurementOption_applyObserve_Call) Run(run func(_a0 metric.ObserveConfig)) *MockMeasurementOption_applyObserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metric.ObserveConfig))
	})
	return _c
}

func (_c *MockMeasurementOption_applyObserve_Call) Return(_a0 metric.ObserveConfig) *MockMeasurementOption_applyObserve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMeasurementOption_applyObserve_Call) RunAndReturn(run func(metric.ObserveConfig) metric.ObserveConfig) *MockMeasurementOption_applyObserve_Call {
	_c.Call.Return(run)
	return _c
}

// applyRecord provides a mock function with given fields: _a0
func (_m *MockMeasurementOption) applyRecord(_a0 metric.RecordConfig) metric.RecordConfig {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for applyRecord")
	}

	var r0 metric.RecordConfig
	if rf, ok := ret.Get(0).(func(metric.RecordConfig) metric.RecordConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(metric.RecordConfig)
	}

	return r0
}

// MockMeasurementOption_applyRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyRecord'
type MockMeasurementOption_applyRecord_Call struct {
	*mock.Call
}

// applyRecord is a helper method to define mock.On call
//   - _a0 metric.RecordConfig
func (_e *MockMeasurementOption_Expecter) applyRecord(_a0 interface{}) *MockMeasurementOption_applyRecord_Call {
	return &MockMeasurementOption_applyRecord_Call{Call: _e.mock.On("applyRecord", _a0)}
}

func (_c *MockMeasurementOption_applyRecord_Call) Run(run func(_a0 metric.RecordConfig)) *MockMeasurementOption_applyRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metric.RecordConfig))
	})
	return _c
}

func (_c *MockMeasurementOption_applyRecord_Call) Return(_a0 metric.RecordConfig) *MockMeasurementOption_applyRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMeasurementOption_applyRecord_Call) RunAndReturn(run func(metric.RecordConfig) metric.RecordConfig) *MockMeasurementOption_applyRecord_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMeasurementOption creates a new instance of MockMeasurementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMeasurementOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMeasurementOption {
	mock := &MockMeasurementOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
