// Code generated by mockery v2.50.1. DO NOT EDIT.

package metric

import (
	mock "github.com/stretchr/testify/mock"
	metric "go.opentelemetry.io/otel/metric"
)

// MockRecordOption is an autogenerated mock type for the RecordOption type
type MockRecordOption struct {
	mock.Mock
}

type MockRecordOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecordOption) EXPECT() *MockRecordOption_Expecter {
	return &MockRecordOption_Expecter{mock: &_m.Mock}
}

// applyRecord provides a mock function with given fields: _a0
func (_m *MockRecordOption) applyRecord(_a0 metric.RecordConfig) metric.RecordConfig {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for applyRecord")
	}

	var r0 metric.RecordConfig
	if rf, ok := ret.Get(0).(func(metric.RecordConfig) metric.RecordConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(metric.RecordConfig)
	}

	return r0
}

// MockRecordOption_applyRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyRecord'
type MockRecordOption_applyRecord_Call struct {
	*mock.Call
}

// applyRecord is a helper method to define mock.On call
//   - _a0 metric.RecordConfig
func (_e *MockRecordOption_Expecter) applyRecord(_a0 interface{}) *MockRecordOption_applyRecord_Call {
	return &MockRecordOption_applyRecord_Call{Call: _e.mock.On("applyRecord", _a0)}
}

func (_c *MockRecordOption_applyRecord_Call) Run(run func(_a0 metric.RecordConfig)) *MockRecordOption_applyRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metric.RecordConfig))
	})
	return _c
}

func (_c *MockRecordOption_applyRecord_Call) Return(_a0 metric.RecordConfig) *MockRecordOption_applyRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecordOption_applyRecord_Call) RunAndReturn(run func(metric.RecordConfig) metric.RecordConfig) *MockRecordOption_applyRecord_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecordOption creates a new instance of MockRecordOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecordOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecordOption {
	mock := &MockRecordOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
