// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockFloat64ObservableUpDownCounterOption creates a new instance of MockFloat64ObservableUpDownCounterOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64ObservableUpDownCounterOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64ObservableUpDownCounterOption {
	mock := &MockFloat64ObservableUpDownCounterOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFloat64ObservableUpDownCounterOption is an autogenerated mock type for the Float64ObservableUpDownCounterOption type
type MockFloat64ObservableUpDownCounterOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockFloat64ObservableUpDownCounterOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64ObservableUpDownCounterOption) EXPECT() *MockFloat64ObservableUpDownCounterOption_Expecter {
	return &MockFloat64ObservableUpDownCounterOption_Expecter{mock: &_m.Mock}
}

// applyFloat64ObservableUpDownCounter provides a mock function for the type MockFloat64ObservableUpDownCounterOption
func (_mock *MockFloat64ObservableUpDownCounterOption) applyFloat64ObservableUpDownCounter(float64ObservableUpDownCounterConfig metric.Float64ObservableUpDownCounterConfig) metric.Float64ObservableUpDownCounterConfig {
	ret := _mock.Called(float64ObservableUpDownCounterConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyFloat64ObservableUpDownCounter")
	}

	var r0 metric.Float64ObservableUpDownCounterConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Float64ObservableUpDownCounterConfig) metric.Float64ObservableUpDownCounterConfig); ok {
		r0 = returnFunc(float64ObservableUpDownCounterConfig)
	} else {
		r0 = ret.Get(0).(metric.Float64ObservableUpDownCounterConfig)
	}
	return r0
}

// MockFloat64ObservableUpDownCounterOption_applyFloat64ObservableUpDownCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyFloat64ObservableUpDownCounter'
type MockFloat64ObservableUpDownCounterOption_applyFloat64ObservableUpDownCounter_Call struct {
	*mock.Call
}

// applyFloat64ObservableUpDownCounter is a helper method to define mock.On call
//   - float64ObservableUpDownCounterConfig metric.Float64ObservableUpDownCounterConfig
func (_e *MockFloat64ObservableUpDownCounterOption_Expecter) applyFloat64ObservableUpDownCounter(float64ObservableUpDownCounterConfig interface{}) *MockFloat64ObservableUpDownCounterOption_applyFloat64ObservableUpDownCounter_Call {
	return &MockFloat64ObservableUpDownCounterOption_applyFloat64ObservableUpDownCounter_Call{Call: _e.mock.On("applyFloat64ObservableUpDownCounter", float64ObservableUpDownCounterConfig)}
}

func (_c *MockFloat64ObservableUpDownCounterOption_applyFloat64ObservableUpDownCounter_Call) Run(run func(float64ObservableUpDownCounterConfig metric.Float64ObservableUpDownCounterConfig)) *MockFloat64ObservableUpDownCounterOption_applyFloat64ObservableUpDownCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Float64ObservableUpDownCounterConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Float64ObservableUpDownCounterConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFloat64ObservableUpDownCounterOption_applyFloat64ObservableUpDownCounter_Call) Return(float64ObservableUpDownCounterConfig1 metric.Float64ObservableUpDownCounterConfig) *MockFloat64ObservableUpDownCounterOption_applyFloat64ObservableUpDownCounter_Call {
	_c.Call.Return(float64ObservableUpDownCounterConfig1)
	return _c
}

func (_c *MockFloat64ObservableUpDownCounterOption_applyFloat64ObservableUpDownCounter_Call) RunAndReturn(run func(float64ObservableUpDownCounterConfig metric.Float64ObservableUpDownCounterConfig) metric.Float64ObservableUpDownCounterConfig) *MockFloat64ObservableUpDownCounterOption_applyFloat64ObservableUpDownCounter_Call {
	_c.Call.Return(run)
	return _c
}
