// Code generated by mockery v2.50.1. DO NOT EDIT.

package metric

import (
	mock "github.com/stretchr/testify/mock"
	metric "go.opentelemetry.io/otel/metric"
)

// MockFloat64Observer is an autogenerated mock type for the Float64Observer type
type MockFloat64Observer struct {
	mock.Mock
}

type MockFloat64Observer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64Observer) EXPECT() *MockFloat64Observer_Expecter {
	return &MockFloat64Observer_Expecter{mock: &_m.Mock}
}

// Observe provides a mock function with given fields: value, options
func (_m *MockFloat64Observer) Observe(value float64, options ...metric.ObserveOption) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, value)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockFloat64Observer_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type MockFloat64Observer_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - value float64
//   - options ...metric.ObserveOption
func (_e *MockFloat64Observer_Expecter) Observe(value interface{}, options ...interface{}) *MockFloat64Observer_Observe_Call {
	return &MockFloat64Observer_Observe_Call{Call: _e.mock.On("Observe",
		append([]interface{}{value}, options...)...)}
}

func (_c *MockFloat64Observer_Observe_Call) Run(run func(value float64, options ...metric.ObserveOption)) *MockFloat64Observer_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]metric.ObserveOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(metric.ObserveOption)
			}
		}
		run(args[0].(float64), variadicArgs...)
	})
	return _c
}

func (_c *MockFloat64Observer_Observe_Call) Return() *MockFloat64Observer_Observe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64Observer_Observe_Call) RunAndReturn(run func(float64, ...metric.ObserveOption)) *MockFloat64Observer_Observe_Call {
	_c.Run(run)
	return _c
}

// float64Observer provides a mock function with no fields
func (_m *MockFloat64Observer) float64Observer() {
	_m.Called()
}

// MockFloat64Observer_float64Observer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'float64Observer'
type MockFloat64Observer_float64Observer_Call struct {
	*mock.Call
}

// float64Observer is a helper method to define mock.On call
func (_e *MockFloat64Observer_Expecter) float64Observer() *MockFloat64Observer_float64Observer_Call {
	return &MockFloat64Observer_float64Observer_Call{Call: _e.mock.On("float64Observer")}
}

func (_c *MockFloat64Observer_float64Observer_Call) Run(run func()) *MockFloat64Observer_float64Observer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFloat64Observer_float64Observer_Call) Return() *MockFloat64Observer_float64Observer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64Observer_float64Observer_Call) RunAndReturn(run func()) *MockFloat64Observer_float64Observer_Call {
	_c.Run(run)
	return _c
}

// NewMockFloat64Observer creates a new instance of MockFloat64Observer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64Observer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64Observer {
	mock := &MockFloat64Observer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
