// Code generated by mockery v2.50.1. DO NOT EDIT.

package metric

import mock "github.com/stretchr/testify/mock"

// MockFloat64Observable is an autogenerated mock type for the Float64Observable type
type MockFloat64Observable struct {
	mock.Mock
}

type MockFloat64Observable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64Observable) EXPECT() *MockFloat64Observable_Expecter {
	return &MockFloat64Observable_Expecter{mock: &_m.Mock}
}

// float64Observable provides a mock function with no fields
func (_m *MockFloat64Observable) float64Observable() {
	_m.Called()
}

// MockFloat64Observable_float64Observable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'float64Observable'
type MockFloat64Observable_float64Observable_Call struct {
	*mock.Call
}

// float64Observable is a helper method to define mock.On call
func (_e *MockFloat64Observable_Expecter) float64Observable() *MockFloat64Observable_float64Observable_Call {
	return &MockFloat64Observable_float64Observable_Call{Call: _e.mock.On("float64Observable")}
}

func (_c *MockFloat64Observable_float64Observable_Call) Run(run func()) *MockFloat64Observable_float64Observable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFloat64Observable_float64Observable_Call) Return() *MockFloat64Observable_float64Observable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64Observable_float64Observable_Call) RunAndReturn(run func()) *MockFloat64Observable_float64Observable_Call {
	_c.Run(run)
	return _c
}

// observable provides a mock function with no fields
func (_m *MockFloat64Observable) observable() {
	_m.Called()
}

// MockFloat64Observable_observable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'observable'
type MockFloat64Observable_observable_Call struct {
	*mock.Call
}

// observable is a helper method to define mock.On call
func (_e *MockFloat64Observable_Expecter) observable() *MockFloat64Observable_observable_Call {
	return &MockFloat64Observable_observable_Call{Call: _e.mock.On("observable")}
}

func (_c *MockFloat64Observable_observable_Call) Run(run func()) *MockFloat64Observable_observable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFloat64Observable_observable_Call) Return() *MockFloat64Observable_observable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64Observable_observable_Call) RunAndReturn(run func()) *MockFloat64Observable_observable_Call {
	_c.Run(run)
	return _c
}

// NewMockFloat64Observable creates a new instance of MockFloat64Observable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64Observable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64Observable {
	mock := &MockFloat64Observable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
