// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockAddOption creates a new instance of MockAddOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddOption {
	mock := &MockAddOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAddOption is an autogenerated mock type for the AddOption type
type MockAddOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockAddOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddOption) EXPECT() *MockAddOption_Expecter {
	return &MockAddOption_Expecter{mock: &_m.Mock}
}

// applyAdd provides a mock function for the type MockAddOption
func (_mock *MockAddOption) applyAdd(addConfig metric.AddConfig) metric.AddConfig {
	ret := _mock.Called(addConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyAdd")
	}

	var r0 metric.AddConfig
	if returnFunc, ok := ret.Get(0).(func(metric.AddConfig) metric.AddConfig); ok {
		r0 = returnFunc(addConfig)
	} else {
		r0 = ret.Get(0).(metric.AddConfig)
	}
	return r0
}

// MockAddOption_applyAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyAdd'
type MockAddOption_applyAdd_Call struct {
	*mock.Call
}

// applyAdd is a helper method to define mock.On call
//   - addConfig metric.AddConfig
func (_e *MockAddOption_Expecter) applyAdd(addConfig interface{}) *MockAddOption_applyAdd_Call {
	return &MockAddOption_applyAdd_Call{Call: _e.mock.On("applyAdd", addConfig)}
}

func (_c *MockAddOption_applyAdd_Call) Run(run func(addConfig metric.AddConfig)) *MockAddOption_applyAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.AddConfig
		if args[0] != nil {
			arg0 = args[0].(metric.AddConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAddOption_applyAdd_Call) Return(addConfig1 metric.AddConfig) *MockAddOption_applyAdd_Call {
	_c.Call.Return(addConfig1)
	return _c
}

func (_c *MockAddOption_applyAdd_Call) RunAndReturn(run func(addConfig metric.AddConfig) metric.AddConfig) *MockAddOption_applyAdd_Call {
	_c.Call.Return(run)
	return _c
}
