// Code generated by mockery v2.50.1. DO NOT EDIT.

package metric

import (
	mock "github.com/stretchr/testify/mock"
	metric "go.opentelemetry.io/otel/metric"
)

// MockInt64HistogramOption is an autogenerated mock type for the Int64HistogramOption type
type MockInt64HistogramOption struct {
	mock.Mock
}

type MockInt64HistogramOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64HistogramOption) EXPECT() *MockInt64HistogramOption_Expecter {
	return &MockInt64HistogramOption_Expecter{mock: &_m.Mock}
}

// applyInt64Histogram provides a mock function with given fields: _a0
func (_m *MockInt64HistogramOption) applyInt64Histogram(_a0 metric.Int64HistogramConfig) metric.Int64HistogramConfig {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for applyInt64Histogram")
	}

	var r0 metric.Int64HistogramConfig
	if rf, ok := ret.Get(0).(func(metric.Int64HistogramConfig) metric.Int64HistogramConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(metric.Int64HistogramConfig)
	}

	return r0
}

// MockInt64HistogramOption_applyInt64Histogram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyInt64Histogram'
type MockInt64HistogramOption_applyInt64Histogram_Call struct {
	*mock.Call
}

// applyInt64Histogram is a helper method to define mock.On call
//   - _a0 metric.Int64HistogramConfig
func (_e *MockInt64HistogramOption_Expecter) applyInt64Histogram(_a0 interface{}) *MockInt64HistogramOption_applyInt64Histogram_Call {
	return &MockInt64HistogramOption_applyInt64Histogram_Call{Call: _e.mock.On("applyInt64Histogram", _a0)}
}

func (_c *MockInt64HistogramOption_applyInt64Histogram_Call) Run(run func(_a0 metric.Int64HistogramConfig)) *MockInt64HistogramOption_applyInt64Histogram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metric.Int64HistogramConfig))
	})
	return _c
}

func (_c *MockInt64HistogramOption_applyInt64Histogram_Call) Return(_a0 metric.Int64HistogramConfig) *MockInt64HistogramOption_applyInt64Histogram_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInt64HistogramOption_applyInt64Histogram_Call) RunAndReturn(run func(metric.Int64HistogramConfig) metric.Int64HistogramConfig) *MockInt64HistogramOption_applyInt64Histogram_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInt64HistogramOption creates a new instance of MockInt64HistogramOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64HistogramOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64HistogramOption {
	mock := &MockInt64HistogramOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
