// Code generated by mockery v2.50.1. DO NOT EDIT.

package metric

import (
	mock "github.com/stretchr/testify/mock"
	metric "go.opentelemetry.io/otel/metric"
)

// MockFloat64ObservableOption is an autogenerated mock type for the Float64ObservableOption type
type MockFloat64ObservableOption struct {
	mock.Mock
}

type MockFloat64ObservableOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64ObservableOption) EXPECT() *MockFloat64ObservableOption_Expecter {
	return &MockFloat64ObservableOption_Expecter{mock: &_m.Mock}
}

// applyFloat64ObservableCounter provides a mock function with given fields: _a0
func (_m *MockFloat64ObservableOption) applyFloat64ObservableCounter(_a0 metric.Float64ObservableCounterConfig) metric.Float64ObservableCounterConfig {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for applyFloat64ObservableCounter")
	}

	var r0 metric.Float64ObservableCounterConfig
	if rf, ok := ret.Get(0).(func(metric.Float64ObservableCounterConfig) metric.Float64ObservableCounterConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(metric.Float64ObservableCounterConfig)
	}

	return r0
}

// MockFloat64ObservableOption_applyFloat64ObservableCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyFloat64ObservableCounter'
type MockFloat64ObservableOption_applyFloat64ObservableCounter_Call struct {
	*mock.Call
}

// applyFloat64ObservableCounter is a helper method to define mock.On call
//   - _a0 metric.Float64ObservableCounterConfig
func (_e *MockFloat64ObservableOption_Expecter) applyFloat64ObservableCounter(_a0 interface{}) *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call {
	return &MockFloat64ObservableOption_applyFloat64ObservableCounter_Call{Call: _e.mock.On("applyFloat64ObservableCounter", _a0)}
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call) Run(run func(_a0 metric.Float64ObservableCounterConfig)) *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metric.Float64ObservableCounterConfig))
	})
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call) Return(_a0 metric.Float64ObservableCounterConfig) *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call) RunAndReturn(run func(metric.Float64ObservableCounterConfig) metric.Float64ObservableCounterConfig) *MockFloat64ObservableOption_applyFloat64ObservableCounter_Call {
	_c.Call.Return(run)
	return _c
}

// applyFloat64ObservableGauge provides a mock function with given fields: _a0
func (_m *MockFloat64ObservableOption) applyFloat64ObservableGauge(_a0 metric.Float64ObservableGaugeConfig) metric.Float64ObservableGaugeConfig {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for applyFloat64ObservableGauge")
	}

	var r0 metric.Float64ObservableGaugeConfig
	if rf, ok := ret.Get(0).(func(metric.Float64ObservableGaugeConfig) metric.Float64ObservableGaugeConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(metric.Float64ObservableGaugeConfig)
	}

	return r0
}

// MockFloat64ObservableOption_applyFloat64ObservableGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyFloat64ObservableGauge'
type MockFloat64ObservableOption_applyFloat64ObservableGauge_Call struct {
	*mock.Call
}

// applyFloat64ObservableGauge is a helper method to define mock.On call
//   - _a0 metric.Float64ObservableGaugeConfig
func (_e *MockFloat64ObservableOption_Expecter) applyFloat64ObservableGauge(_a0 interface{}) *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call {
	return &MockFloat64ObservableOption_applyFloat64ObservableGauge_Call{Call: _e.mock.On("applyFloat64ObservableGauge", _a0)}
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call) Run(run func(_a0 metric.Float64ObservableGaugeConfig)) *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metric.Float64ObservableGaugeConfig))
	})
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call) Return(_a0 metric.Float64ObservableGaugeConfig) *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call) RunAndReturn(run func(metric.Float64ObservableGaugeConfig) metric.Float64ObservableGaugeConfig) *MockFloat64ObservableOption_applyFloat64ObservableGauge_Call {
	_c.Call.Return(run)
	return _c
}

// applyFloat64ObservableUpDownCounter provides a mock function with given fields: _a0
func (_m *MockFloat64ObservableOption) applyFloat64ObservableUpDownCounter(_a0 metric.Float64ObservableUpDownCounterConfig) metric.Float64ObservableUpDownCounterConfig {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for applyFloat64ObservableUpDownCounter")
	}

	var r0 metric.Float64ObservableUpDownCounterConfig
	if rf, ok := ret.Get(0).(func(metric.Float64ObservableUpDownCounterConfig) metric.Float64ObservableUpDownCounterConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(metric.Float64ObservableUpDownCounterConfig)
	}

	return r0
}

// MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyFloat64ObservableUpDownCounter'
type MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call struct {
	*mock.Call
}

// applyFloat64ObservableUpDownCounter is a helper method to define mock.On call
//   - _a0 metric.Float64ObservableUpDownCounterConfig
func (_e *MockFloat64ObservableOption_Expecter) applyFloat64ObservableUpDownCounter(_a0 interface{}) *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call {
	return &MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call{Call: _e.mock.On("applyFloat64ObservableUpDownCounter", _a0)}
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call) Run(run func(_a0 metric.Float64ObservableUpDownCounterConfig)) *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metric.Float64ObservableUpDownCounterConfig))
	})
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call) Return(_a0 metric.Float64ObservableUpDownCounterConfig) *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call) RunAndReturn(run func(metric.Float64ObservableUpDownCounterConfig) metric.Float64ObservableUpDownCounterConfig) *MockFloat64ObservableOption_applyFloat64ObservableUpDownCounter_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFloat64ObservableOption creates a new instance of MockFloat64ObservableOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64ObservableOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64ObservableOption {
	mock := &MockFloat64ObservableOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
