// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockFloat64GaugeOption creates a new instance of MockFloat64GaugeOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64GaugeOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64GaugeOption {
	mock := &MockFloat64GaugeOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFloat64GaugeOption is an autogenerated mock type for the Float64GaugeOption type
type MockFloat64GaugeOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockFloat64GaugeOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64GaugeOption) EXPECT() *MockFloat64GaugeOption_Expecter {
	return &MockFloat64GaugeOption_Expecter{mock: &_m.Mock}
}

// applyFloat64Gauge provides a mock function for the type MockFloat64GaugeOption
func (_mock *MockFloat64GaugeOption) applyFloat64Gauge(float64GaugeConfig metric.Float64GaugeConfig) metric.Float64GaugeConfig {
	ret := _mock.Called(float64GaugeConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyFloat64Gauge")
	}

	var r0 metric.Float64GaugeConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Float64GaugeConfig) metric.Float64GaugeConfig); ok {
		r0 = returnFunc(float64GaugeConfig)
	} else {
		r0 = ret.Get(0).(metric.Float64GaugeConfig)
	}
	return r0
}

// MockFloat64GaugeOption_applyFloat64Gauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyFloat64Gauge'
type MockFloat64GaugeOption_applyFloat64Gauge_Call struct {
	*mock.Call
}

// applyFloat64Gauge is a helper method to define mock.On call
//   - float64GaugeConfig metric.Float64GaugeConfig
func (_e *MockFloat64GaugeOption_Expecter) applyFloat64Gauge(float64GaugeConfig interface{}) *MockFloat64GaugeOption_applyFloat64Gauge_Call {
	return &MockFloat64GaugeOption_applyFloat64Gauge_Call{Call: _e.mock.On("applyFloat64Gauge", float64GaugeConfig)}
}

func (_c *MockFloat64GaugeOption_applyFloat64Gauge_Call) Run(run func(float64GaugeConfig metric.Float64GaugeConfig)) *MockFloat64GaugeOption_applyFloat64Gauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Float64GaugeConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Float64GaugeConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFloat64GaugeOption_applyFloat64Gauge_Call) Return(float64GaugeConfig1 metric.Float64GaugeConfig) *MockFloat64GaugeOption_applyFloat64Gauge_Call {
	_c.Call.Return(float64GaugeConfig1)
	return _c
}

func (_c *MockFloat64GaugeOption_applyFloat64Gauge_Call) RunAndReturn(run func(float64GaugeConfig metric.Float64GaugeConfig) metric.Float64GaugeConfig) *MockFloat64GaugeOption_applyFloat64Gauge_Call {
	_c.Call.Return(run)
	return _c
}
