// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockInt64UpDownCounterOption creates a new instance of MockInt64UpDownCounterOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64UpDownCounterOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64UpDownCounterOption {
	mock := &MockInt64UpDownCounterOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInt64UpDownCounterOption is an autogenerated mock type for the Int64UpDownCounterOption type
type MockInt64UpDownCounterOption struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockInt64UpDownCounterOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64UpDownCounterOption) EXPECT() *MockInt64UpDownCounterOption_Expecter {
	return &MockInt64UpDownCounterOption_Expecter{mock: &_m.Mock}
}

// applyInt64UpDownCounter provides a mock function for the type MockInt64UpDownCounterOption
func (_mock *MockInt64UpDownCounterOption) applyInt64UpDownCounter(int64UpDownCounterConfig metric.Int64UpDownCounterConfig) metric.Int64UpDownCounterConfig {
	ret := _mock.Called(int64UpDownCounterConfig)

	if len(ret) == 0 {
		panic("no return value specified for applyInt64UpDownCounter")
	}

	var r0 metric.Int64UpDownCounterConfig
	if returnFunc, ok := ret.Get(0).(func(metric.Int64UpDownCounterConfig) metric.Int64UpDownCounterConfig); ok {
		r0 = returnFunc(int64UpDownCounterConfig)
	} else {
		r0 = ret.Get(0).(metric.Int64UpDownCounterConfig)
	}
	return r0
}

// MockInt64UpDownCounterOption_applyInt64UpDownCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applyInt64UpDownCounter'
type MockInt64UpDownCounterOption_applyInt64UpDownCounter_Call struct {
	*mock.Call
}

// applyInt64UpDownCounter is a helper method to define mock.On call
//   - int64UpDownCounterConfig metric.Int64UpDownCounterConfig
func (_e *MockInt64UpDownCounterOption_Expecter) applyInt64UpDownCounter(int64UpDownCounterConfig interface{}) *MockInt64UpDownCounterOption_applyInt64UpDownCounter_Call {
	return &MockInt64UpDownCounterOption_applyInt64UpDownCounter_Call{Call: _e.mock.On("applyInt64UpDownCounter", int64UpDownCounterConfig)}
}

func (_c *MockInt64UpDownCounterOption_applyInt64UpDownCounter_Call) Run(run func(int64UpDownCounterConfig metric.Int64UpDownCounterConfig)) *MockInt64UpDownCounterOption_applyInt64UpDownCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Int64UpDownCounterConfig
		if args[0] != nil {
			arg0 = args[0].(metric.Int64UpDownCounterConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInt64UpDownCounterOption_applyInt64UpDownCounter_Call) Return(int64UpDownCounterConfig1 metric.Int64UpDownCounterConfig) *MockInt64UpDownCounterOption_applyInt64UpDownCounter_Call {
	_c.Call.Return(int64UpDownCounterConfig1)
	return _c
}

func (_c *MockInt64UpDownCounterOption_applyInt64UpDownCounter_Call) RunAndReturn(run func(int64UpDownCounterConfig metric.Int64UpDownCounterConfig) metric.Int64UpDownCounterConfig) *MockInt64UpDownCounterOption_applyInt64UpDownCounter_Call {
	_c.Call.Return(run)
	return _c
}
