// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockInt64Gauge creates a new instance of MockInt64Gauge. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64Gauge(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64Gauge {
	mock := &MockInt64Gauge{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInt64Gauge is an autogenerated mock type for the Int64Gauge type
type MockInt64Gauge struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockInt64Gauge_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64Gauge) EXPECT() *MockInt64Gauge_Expecter {
	return &MockInt64Gauge_Expecter{mock: &_m.Mock}
}

// Record provides a mock function for the type MockInt64Gauge
func (_mock *MockInt64Gauge) Record(ctx context.Context, value int64, options ...metric.RecordOption) {
	// metric.RecordOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, value)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockInt64Gauge_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockInt64Gauge_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - value int64
//   - options ...metric.RecordOption
func (_e *MockInt64Gauge_Expecter) Record(ctx interface{}, value interface{}, options ...interface{}) *MockInt64Gauge_Record_Call {
	return &MockInt64Gauge_Record_Call{Call: _e.mock.On("Record",
		append([]interface{}{ctx, value}, options...)...)}
}

func (_c *MockInt64Gauge_Record_Call) Run(run func(ctx context.Context, value int64, options ...metric.RecordOption)) *MockInt64Gauge_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []metric.RecordOption
		variadicArgs := make([]metric.RecordOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(metric.RecordOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockInt64Gauge_Record_Call) Return() *MockInt64Gauge_Record_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInt64Gauge_Record_Call) RunAndReturn(run func(ctx context.Context, value int64, options ...metric.RecordOption)) *MockInt64Gauge_Record_Call {
	_c.Run(run)
	return _c
}

// int64Gauge provides a mock function for the type MockInt64Gauge
func (_mock *MockInt64Gauge) int64Gauge() {
	_mock.Called()
	return
}

// MockInt64Gauge_int64Gauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'int64Gauge'
type MockInt64Gauge_int64Gauge_Call struct {
	*mock.Call
}

// int64Gauge is a helper method to define mock.On call
func (_e *MockInt64Gauge_Expecter) int64Gauge() *MockInt64Gauge_int64Gauge_Call {
	return &MockInt64Gauge_int64Gauge_Call{Call: _e.mock.On("int64Gauge")}
}

func (_c *MockInt64Gauge_int64Gauge_Call) Run(run func()) *MockInt64Gauge_int64Gauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInt64Gauge_int64Gauge_Call) Return() *MockInt64Gauge_int64Gauge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInt64Gauge_int64Gauge_Call) RunAndReturn(run func()) *MockInt64Gauge_int64Gauge_Call {
	_c.Run(run)
	return _c
}
