// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metric

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"

	_metricotelembedded "go.opentelemetry.io/otel/metric/embedded"
	_traceotelembedded "go.opentelemetry.io/otel/trace/embedded"
)

// NewMockFloat64Histogram creates a new instance of MockFloat64Histogram. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat64Histogram(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat64Histogram {
	mock := &MockFloat64Histogram{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFloat64Histogram is an autogenerated mock type for the Float64Histogram type
type MockFloat64Histogram struct {
	mock.Mock
	_metricotelembedded.Meter
	_metricotelembedded.MeterProvider
	_traceotelembedded.Span
	_traceotelembedded.Tracer
	_traceotelembedded.TracerProvider
	_metricotelembedded.Float64Histogram
}

type MockFloat64Histogram_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat64Histogram) EXPECT() *MockFloat64Histogram_Expecter {
	return &MockFloat64Histogram_Expecter{mock: &_m.Mock}
}

// Record provides a mock function for the type MockFloat64Histogram
func (_mock *MockFloat64Histogram) Record(ctx context.Context, incr float64, options ...metric.RecordOption) {
	// metric.RecordOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, incr)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockFloat64Histogram_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockFloat64Histogram_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - incr float64
//   - options ...metric.RecordOption
func (_e *MockFloat64Histogram_Expecter) Record(ctx interface{}, incr interface{}, options ...interface{}) *MockFloat64Histogram_Record_Call {
	return &MockFloat64Histogram_Record_Call{Call: _e.mock.On("Record",
		append([]interface{}{ctx, incr}, options...)...)}
}

func (_c *MockFloat64Histogram_Record_Call) Run(run func(ctx context.Context, incr float64, options ...metric.RecordOption)) *MockFloat64Histogram_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 []metric.RecordOption
		variadicArgs := make([]metric.RecordOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(metric.RecordOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFloat64Histogram_Record_Call) Return() *MockFloat64Histogram_Record_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64Histogram_Record_Call) RunAndReturn(run func(ctx context.Context, incr float64, options ...metric.RecordOption)) *MockFloat64Histogram_Record_Call {
	_c.Run(run)
	return _c
}

// float64Histogram provides a mock function for the type MockFloat64Histogram
func (_mock *MockFloat64Histogram) float64Histogram() {
	_mock.Called()
	return
}

// MockFloat64Histogram_float64Histogram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'float64Histogram'
type MockFloat64Histogram_float64Histogram_Call struct {
	*mock.Call
}

// float64Histogram is a helper method to define mock.On call
func (_e *MockFloat64Histogram_Expecter) float64Histogram() *MockFloat64Histogram_float64Histogram_Call {
	return &MockFloat64Histogram_float64Histogram_Call{Call: _e.mock.On("float64Histogram")}
}

func (_c *MockFloat64Histogram_float64Histogram_Call) Run(run func()) *MockFloat64Histogram_float64Histogram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFloat64Histogram_float64Histogram_Call) Return() *MockFloat64Histogram_float64Histogram_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFloat64Histogram_float64Histogram_Call) RunAndReturn(run func()) *MockFloat64Histogram_float64Histogram_Call {
	_c.Run(run)
	return _c
}
