// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package store

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const getUsersByID = `-- name: GetUsersByID :batchone
SELECT id, username, email, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUsersByIDBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) GetUsersByID(ctx context.Context, db DBTX, id []int64) *GetUsersByIDBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(getUsersByID, vals...)
	}
	br := db.SendBatch(ctx, batch)
	return &GetUsersByIDBatchResults{br, len(id), false}
}

func (b *GetUsersByIDBatchResults) QueryRow(f func(int, User, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i User
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *GetUsersByIDBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertUsers = `-- name: InsertUsers :batchexec
INSERT INTO users (username, email)
VALUES ($1, $2)
`

type InsertUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertUsersParams struct {
	Username string
	Email    string
}

func (q *Queries) InsertUsers(ctx context.Context, db DBTX, arg []InsertUsersParams) *InsertUsersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Username,
			a.Email,
		}
		batch.Queue(insertUsers, vals...)
	}
	br := db.SendBatch(ctx, batch)
	return &InsertUsersBatchResults{br, len(arg), false}
}

func (b *InsertUsersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
