// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForCopyUsers implements pgx.CopyFromSource.
type iteratorForCopyUsers struct {
	rows                 []CopyUsersParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyUsers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyUsers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Username,
		r.rows[0].Email,
	}, nil
}

func (r iteratorForCopyUsers) Err() error {
	return nil
}

func (q *Queries) CopyUsers(ctx context.Context, db DBTX, arg []CopyUsersParams) (int64, error) {
	return db.CopyFrom(ctx, []string{"users"}, []string{"username", "email"}, &iteratorForCopyUsers{rows: arg})
}
