// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, post_id, user_id, content, created_at
`

func (q *Queries) CreateComment(ctx context.Context, db DBTX, postID int64, userID int64, content string) (Comment, error) {
	row := db.QueryRow(ctx, createComment, postID, userID, content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, title, content)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, content, created_at, updated_at
`

func (q *Queries) CreatePost(ctx context.Context, db DBTX, userID int64, title string, content string) (Post, error) {
	row := db.QueryRow(ctx, createPost, userID, title, content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostWithStats = `-- name: GetPostWithStats :one
SELECT
    p.id,
    p.user_id,
    p.title,
    p.content,
    p.created_at,
    p.updated_at,
    u.username,
    COUNT(c.id) AS comment_count
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN comments c ON p.id = c.post_id
WHERE p.id = $1
GROUP BY p.id, u.username
`

type GetPostWithStatsRow struct {
	ID           int64
	UserID       int64
	Title        string
	Content      string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	Username     string
	CommentCount int64
}

func (q *Queries) GetPostWithStats(ctx context.Context, db DBTX, id int64) (GetPostWithStatsRow, error) {
	row := db.QueryRow(ctx, getPostWithStats, id)
	var i GetPostWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.CommentCount,
	)
	return i, err
}
