// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CopyUsers(ctx context.Context, db DBTX, arg []CopyUsersParams) (int64, error)
	CreateComment(ctx context.Context, db DBTX, postID int64, userID int64, content string) (Comment, error)
	CreatePost(ctx context.Context, db DBTX, userID int64, title string, content string) (Post, error)
	CreateUser(ctx context.Context, db DBTX, username string, email string) (User, error)
	DeleteUser(ctx context.Context, db DBTX, id int64) error
	GetPostWithStats(ctx context.Context, db DBTX, id int64) (GetPostWithStatsRow, error)
	GetUserByID(ctx context.Context, db DBTX, id int64) (User, error)
	GetUsersByID(ctx context.Context, db DBTX, id []int64) *GetUsersByIDBatchResults
	InsertUsers(ctx context.Context, db DBTX, arg []InsertUsersParams) *InsertUsersBatchResults
	ListUsers(ctx context.Context, db DBTX, limit int32) ([]User, error)
	UpdateUserEmail(ctx context.Context, db DBTX, iD int64, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
