// Code generated by mockery v2.50.1. DO NOT EDIT.

package trace

import (
	mock "github.com/stretchr/testify/mock"
	trace "go.opentelemetry.io/otel/trace"
)

// MocktracerOptionFunc is an autogenerated mock type for the tracerOptionFunc type
type MocktracerOptionFunc struct {
	mock.Mock
}

type MocktracerOptionFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MocktracerOptionFunc) EXPECT() *MocktracerOptionFunc_Expecter {
	return &MocktracerOptionFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MocktracerOptionFunc) Execute(_a0 trace.TracerConfig) trace.TracerConfig {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 trace.TracerConfig
	if rf, ok := ret.Get(0).(func(trace.TracerConfig) trace.TracerConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(trace.TracerConfig)
	}

	return r0
}

// MocktracerOptionFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MocktracerOptionFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 trace.TracerConfig
func (_e *MocktracerOptionFunc_Expecter) Execute(_a0 interface{}) *MocktracerOptionFunc_Execute_Call {
	return &MocktracerOptionFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MocktracerOptionFunc_Execute_Call) Run(run func(_a0 trace.TracerConfig)) *MocktracerOptionFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(trace.TracerConfig))
	})
	return _c
}

func (_c *MocktracerOptionFunc_Execute_Call) Return(_a0 trace.TracerConfig) *MocktracerOptionFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocktracerOptionFunc_Execute_Call) RunAndReturn(run func(trace.TracerConfig) trace.TracerConfig) *MocktracerOptionFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocktracerOptionFunc creates a new instance of MocktracerOptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktracerOptionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocktracerOptionFunc {
	mock := &MocktracerOptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
