// Code generated by mockery v2.50.1. DO NOT EDIT.

package trace

import (
	mock "github.com/stretchr/testify/mock"
	trace "go.opentelemetry.io/otel/trace"
)

// MockSpanStartOption is an autogenerated mock type for the SpanStartOption type
type MockSpanStartOption struct {
	mock.Mock
}

type MockSpanStartOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpanStartOption) EXPECT() *MockSpanStartOption_Expecter {
	return &MockSpanStartOption_Expecter{mock: &_m.Mock}
}

// applySpanStart provides a mock function with given fields: _a0
func (_m *MockSpanStartOption) applySpanStart(_a0 trace.SpanConfig) trace.SpanConfig {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for applySpanStart")
	}

	var r0 trace.SpanConfig
	if rf, ok := ret.Get(0).(func(trace.SpanConfig) trace.SpanConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(trace.SpanConfig)
	}

	return r0
}

// MockSpanStartOption_applySpanStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'applySpanStart'
type MockSpanStartOption_applySpanStart_Call struct {
	*mock.Call
}

// applySpanStart is a helper method to define mock.On call
//   - _a0 trace.SpanConfig
func (_e *MockSpanStartOption_Expecter) applySpanStart(_a0 interface{}) *MockSpanStartOption_applySpanStart_Call {
	return &MockSpanStartOption_applySpanStart_Call{Call: _e.mock.On("applySpanStart", _a0)}
}

func (_c *MockSpanStartOption_applySpanStart_Call) Run(run func(_a0 trace.SpanConfig)) *MockSpanStartOption_applySpanStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(trace.SpanConfig))
	})
	return _c
}

func (_c *MockSpanStartOption_applySpanStart_Call) Return(_a0 trace.SpanConfig) *MockSpanStartOption_applySpanStart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSpanStartOption_applySpanStart_Call) RunAndReturn(run func(trace.SpanConfig) trace.SpanConfig) *MockSpanStartOption_applySpanStart_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSpanStartOption creates a new instance of MockSpanStartOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpanStartOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpanStartOption {
	mock := &MockSpanStartOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
