// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package integration_test

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertUsers = `-- name: InsertUsers :batchexec
INSERT INTO users (username, email)
VALUES ($1, $2)
`

type InsertUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertUsersParams struct {
	Username string `db:"username" json:"username"`
	Email    string `db:"email" json:"email"`
}

// Batch query - sqlc batches every queued statement under the same query name
func (q *Queries) InsertUsers(ctx context.Context, db DBTX, arg []InsertUsersParams) *InsertUsersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Username,
			a.Email,
		}
		batch.Queue(insertUsers, vals...)
	}
	br := db.SendBatch(ctx, batch)
	return &InsertUsersBatchResults{br, len(arg), false}
}

func (b *InsertUsersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
