// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: integration_test.sql

package integration_test

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, post_id, user_id, content, created_at
`

// Comment queries
func (q *Queries) CreateComment(ctx context.Context, db DBTX, postID int64, userID int64, content string) (Comment, error) {
	row := db.QueryRow(ctx, createComment, postID, userID, content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, title, content)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, content, created_at, updated_at
`

// Post queries
func (q *Queries) CreatePost(ctx context.Context, db DBTX, userID int64, title string, content string) (Post, error) {
	row := db.QueryRow(ctx, createPost, userID, title, content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email)
VALUES ($1, $2)
RETURNING id, username, email, created_at, updated_at
`

// User queries
func (q *Queries) CreateUser(ctx context.Context, db DBTX, username string, email string) (User, error) {
	row := db.QueryRow(ctx, createUser, username, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, deleteComment, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, deletePost, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, deleteUser, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, user_id, title, content, created_at, updated_at
FROM posts
WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, db DBTX, id int64) (Post, error) {
	row := db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostWithStats = `-- name: GetPostWithStats :one
SELECT 
    p.id, 
    p.user_id, 
    p.title, 
    p.content, 
    p.created_at, 
    p.updated_at,
    u.username,
    COUNT(c.id) as comment_count
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN comments c ON p.id = c.post_id
WHERE p.id = $1
GROUP BY p.id, u.username
`

type GetPostWithStatsRow struct {
	ID           int64            `db:"id" json:"id"`
	UserID       int64            `db:"user_id" json:"user_id"`
	Title        string           `db:"title" json:"title"`
	Content      string           `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Username     string           `db:"username" json:"username"`
	CommentCount int64            `db:"comment_count" json:"comment_count"`
}

// Complex query - post with user and comment count
func (q *Queries) GetPostWithStats(ctx context.Context, db DBTX, id int64) (GetPostWithStatsRow, error) {
	row := db.QueryRow(ctx, getPostWithStats, id)
	var i GetPostWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.CommentCount,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, db DBTX, id int64) (User, error) {
	row := db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, created_at, updated_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, db DBTX, username string) (User, error) {
	row := db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPosts = `-- name: ListAllPosts :many
SELECT id, user_id, title, content, created_at, updated_at
FROM posts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

func (q *Queries) ListAllPosts(ctx context.Context, db DBTX, limit int32, offset int32) ([]Post, error) {
	rows, err := db.Query(ctx, listAllPosts, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByPostID = `-- name: ListCommentsByPostID :many
SELECT id, post_id, user_id, content, created_at
FROM comments
WHERE post_id = $1
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListCommentsByPostID(ctx context.Context, db DBTX, postID int64, limit int32, offset int32) ([]Comment, error) {
	rows, err := db.Query(ctx, listCommentsByPostID, postID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUserID = `-- name: ListPostsByUserID :many
SELECT id, user_id, title, content, created_at, updated_at
FROM posts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListPostsByUserID(ctx context.Context, db DBTX, userID int64, limit int32, offset int32) ([]Post, error) {
	rows, err := db.Query(ctx, listPostsByUserID, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

func (q *Queries) ListUsers(ctx context.Context, db DBTX, limit int32, offset int32) ([]User, error) {
	rows, err := db.Query(ctx, listUsers, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, email, created_at, updated_at
`

func (q *Queries) UpdateUserEmail(ctx context.Context, db DBTX, iD int64, email string) (User, error) {
	row := db.QueryRow(ctx, updateUserEmail, iD, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
