// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package integration_test

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int64            `db:"id" json:"id"`
	PostID    int64            `db:"post_id" json:"post_id"`
	UserID    int64            `db:"user_id" json:"user_id"`
	Content   string           `db:"content" json:"content"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Post struct {
	ID        int64            `db:"id" json:"id"`
	UserID    int64            `db:"user_id" json:"user_id"`
	Title     string           `db:"title" json:"title"`
	Content   string           `db:"content" json:"content"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        int64            `db:"id" json:"id"`
	Username  string           `db:"username" json:"username"`
	Email     string           `db:"email" json:"email"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
