// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package integration_test

import (
	"context"
)

type Querier interface {
	// Comment queries
	CreateComment(ctx context.Context, db DBTX, postID int64, userID int64, content string) (Comment, error)
	// Post queries
	CreatePost(ctx context.Context, db DBTX, userID int64, title string, content string) (Post, error)
	// User queries
	CreateUser(ctx context.Context, db DBTX, username string, email string) (User, error)
	DeleteComment(ctx context.Context, db DBTX, id int64) error
	DeletePost(ctx context.Context, db DBTX, id int64) error
	DeleteUser(ctx context.Context, db DBTX, id int64) error
	GetPostByID(ctx context.Context, db DBTX, id int64) (Post, error)
	// Complex query - post with user and comment count
	GetPostWithStats(ctx context.Context, db DBTX, id int64) (GetPostWithStatsRow, error)
	GetUserByID(ctx context.Context, db DBTX, id int64) (User, error)
	GetUserByUsername(ctx context.Context, db DBTX, username string) (User, error)
	// Batch query - sqlc batches every queued statement under the same query name
	InsertUsers(ctx context.Context, db DBTX, arg []InsertUsersParams) *InsertUsersBatchResults
	ListAllPosts(ctx context.Context, db DBTX, limit int32, offset int32) ([]Post, error)
	ListCommentsByPostID(ctx context.Context, db DBTX, postID int64, limit int32, offset int32) ([]Comment, error)
	ListPostsByUserID(ctx context.Context, db DBTX, userID int64, limit int32, offset int32) ([]Post, error)
	ListUsers(ctx context.Context, db DBTX, limit int32, offset int32) ([]User, error)
	UpdateUserEmail(ctx context.Context, db DBTX, iD int64, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
